name: Run Selenium Tests on Safari

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-safari:
    runs-on: macos-latest   # Safari only runs on macOS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Start Safari Driver
        run: |
          safaridriver --enable
          safaridriver --version

      - name: Run Tests
        run: mvn clean test -Dbrowser=safari
