name: Deploy Reports
on:
  push:
    branches:
      - TestGitHubPages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Allure
        run: sudo apt-get install -y allure

      - name: Generate Report
        run: allure generate allure-results --clean -o docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
